### ISSUE TITLE
Bot in encrypted room

### ISSUE THREAD

**Issue by aleixq** [turt2live/matrix-js-bot-sdk#84] opened 2020-05-17 15:10 UTC
I am starting with matrix bot coding. I can't see how olm can be used  to be able to run bots in a e2ee rooms.

I'm missing something?

thank's, and excuse my ignorance if any...

**Comment by Sorunome** [comment] 2020-05-17 15:45
This library doesn't do olm.

**Comment by turt2live** [comment] 2020-05-18 06:22
Duplicate of https://github.com/turt2live/matrix-js-bot-sdk/issues/7

Please use Pantalaimon in the meantime.

**Closed by turt2live** 2020-05-18 06:22 UTC
