### ISSUE TITLE
Getting metrics for appservice users is hard

### ISSUE THREAD

**Issue by Half-Shot** [turt2live/matrix-js-bot-sdk#47] opened 2019-07-18 08:03 UTC
Because each MatrixClient has it's own metrics counter, which makes them hard to bind to. Can appservices bind all intents to the same metrics counter, or alternatively expose a way for a bridge to bind to every MatrixClient in some way.

**Comment by turt2live** [comment] 2019-07-18 13:33
Duplicate of https://github.com/turt2live/matrix-js-bot-sdk/issues/20

**Closed by turt2live** 2019-07-18 13:33 UTC
