### ISSUE TITLE
Expose a way to listen for outbound http requests in order to provide metrics

### ISSUE THREAD

**Issue by Half-Shot** [turt2live/matrix-js-bot-sdk#29] opened 2019-06-17 09:44 UTC
Similarly to how the matrix-appservice-bridge sdk does it.

**Comment by turt2live** [comment] 2019-06-17 15:06
Duplicate of https://github.com/turt2live/matrix-js-bot-sdk/issues/20

**Closed by turt2live** 2019-06-17 15:06 UTC
